<?php
/**
 * new-cart Configuration
 * Generated by install wizard on 2026-04-04 19:05:55.
 */

// Database
define('DB_HOST',    'localhost');
define('DB_NAME',    'new_cart');
define('DB_USER',    'new_cart');
define('DB_PASS',    'Nafoi111$2');
define('DB_PREFIX',  'nc_');
define('DB_CHARSET', 'utf8mb4');

// Paths
define('DIR_ROOT',     __DIR__ . '/../');
define('DIR_CTL',      DIR_ROOT . 'ctl/');
define('DIR_TPL',      DIR_ROOT . 'tpl/');
define('DIR_LIB',      DIR_ROOT . 'lib/');
define('DIR_CACHE',    DIR_ROOT . 'cache/');
define('DIR_IMG',      DIR_ROOT . 'img/');
define('DIR_USERMODS', DIR_ROOT . 'usermods/');
define('DIR_ADMIN',    DIR_ROOT . 'admin/');
define('DIR_INSTALL',  DIR_ROOT . 'install/');

// URLs
define('URL_ROOT',       '/');
define('URL_ADMIN',      '/Cc7DZbWFVDSh/');
define('URL_ADMIN_REAL', '/admin/');
define('URL_IMG',        '/img/');

// Admin path (public-facing URL segment)
define('ADMIN_PATH', 'Cc7DZbWFVDSh');

// Site
define('SITE_NAME',     'My Store');
define('SITE_CURRENCY', '$');
define('SITE_EMAIL',    'BILLTHETAILOR@GMAIL.COM');

// Error handling
define('DISPLAY_ERRORS', false);
define('LOG_ERRORS',     true);
define('ERROR_LOG',      DIR_ROOT . 'logs/error.log');

// Session
define('SESSION_NAME',     'newcart');
define('SESSION_LIFETIME', 86400);

// Smarty
define('SMARTY_FORCE_COMPILE', false);
define('SMARTY_CACHING',       false);